version: "3.9"
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=Asia/Ho_Chi_Minh
      - N8N_DISABLE_FILE_SYSTEM_ACCESS=false
    volumes:
      - ./n8n_data:/home/node/.n8n
      # Ổ đĩa chung để n8n thả file vào
      - shared-data:/data
    restart: unless-stopped

  rf-runner:
    image: marketsquare/robotframework-browser:latest
    container_name: rf-runner
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      # Map thư mục 'rf' (chứa cả .robot và trigger_robot.py)
      - ./rf:/opt/robotframework/tests:rw
      # Ổ đĩa chung để robot lấy file ra
      - shared-data:/data

    # Lệnh này sẽ cài Flask và chạy server thay vì sleep
    command: >
      bash -c "pip install Flask && 
               python /opt/robotframework/tests/trigger_robot.py"
    restart: unless-stopped

# Định nghĩa các ổ đĩa
volumes:
  n8n_data:
  shared-data:
